version: '3'

services:
  frontend:
    image: node:20-alpine
    command: sh -c "yarn install && yarn run dev --port=3000 --host"
    user: 1000:1000
    deploy:
      restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 5
          window: 60s
    networks:
      messenger:
        ipv4_address: 10.5.1.3
    env_file:
      - .frontend.env
    ports:
      - 80:3000
    working_dir: /frontend
    volumes:
      - ./web_frontend:/frontend

  api:
    image: msg_api_dev
    command: conda run --no-capture-output -n cenv flask --app flaskr run --debug --host=10.5.1.10 --port=80
    user: 1000:1000 
    deploy:
      restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 5
          window: 60s
    networks:
      messenger:
        ipv4_address: 10.5.1.10
    ports:
      - 8090:80
    env_file:
      - .api.env
      - .postgresql.env
    depends_on:
      - postgres
    working_dir: /api
    volumes:
      - ./api:/api
  
  api_uwsgi:
    build:
      context: api
      target: prod
    
    networks:
      messenger:
        ipv4_address: 10.5.1.11
    ports: 
      - 443:443
      - 47485:80
    env_file:
      - .api.env
      - .postgresql.env
    volumes:
      - ./crt:/crt

  frontend_prod: 
    build:
      context: web_frontend 
      target: serve
      args:
        - apiURI=${PROD_API_URI}
        - apiURL=${PROD_API_URL}
    networks:
      messenger:
        ipv4_address: 10.5.1.12
    ports: 
      - 3000:80

  postgres:
    image: postgres:16-alpine
    restart: always
    networks:
      messenger:
        ipv4_address: 10.5.1.100
    environment:
      PGDATA: /data/db
    volumes:
      - pgstorage:/data/db
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - .postgresql.env
  
  adminer:
    image: adminer
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s    
    networks:
      messenger:
        ipv4_address: 10.5.1.101    
    ports:
      - 8081:8080

  nginx:
    build:
      context: nginx

    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    networks:
      messenger:
        ipv4_address: 10.5.1.80

    ports:
      - 8080:80
    

volumes:
  pgstorage:     

networks:
  messenger:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
