spring:
  profiles:
    active: "prod"
  datasource:
    url: jdbc:${API_POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AS_ISSUER_URI}
          jwk-set-uri: ${AS_JWKS_URI}

server:
  error:
    whitelabel:
      enabled: false
