spring:
  profiles:
    active: "prod"
  datasource:
    url: jdbc:${AUTH_SERVICE_POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ${GOOGLE_APPLICATION_CLIENT_ID}
            client-secret: ${GOOGLE_APPLICATION_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - openid
              - email
              - profile

server:
  error:
    whitelabel:
      enabled: false
  port: 80
